<#import "parts/common.ftlh" as c>
<#include "parts/security.ftlh">

<@c.page>
    <div class="jumbotron" style="background: #437f4b">
        <h1 class="display-4">Flower Supplier</h1>
        <p class="lead">Приложение создано для снабжения торговых пунктов</p>
        <hr class="my-4">
        <p>Зарегистрируйтесь и посмотрите наш список товаров</p>
        <a class="btn btn-green text-white btn-lg" href="#" role="button">Что нового?</a>
    </div>
</@c.page>
